---
version: '3'
services:
  postgresql:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_MULTIPLE_DATABASES: forumapi,forumapi_test
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ../.data-forum-api/postgresql:/var/lib/postgresql/data/pgdata
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    env_file:
      - ./.env
      # - ./.env_init
